### ISSUE TITLE
Unexpected compilation error after upgrade to 2.20.4 using Scala 2.13

### ISSUE THREAD

**Issue by fggarcia** [plokhotnyuk/jsoniter-scala#982]
When compiling with new 2.20.4 version... 2.20.3 was okey

![image](https://user-images.githubusercontent.com/1306596/214923959-5b404dbd-d590-4a54-bcbf-3d6d0ba34945.png)

**Comment by plokhotnyuk** [comment]
@fggarcia Thanks for reporting! I missed the `clean` command before the `release` call.

I'll clean up target directories and cut v2.20.5.

**Comment by plokhotnyuk** [comment]
The v2.20.5 release is already available on the Maven Central

**Comment by kyri-petrou** [comment]
Hi there. The same issue seems to happen with v2.20.5.

**Comment by plokhotnyuk** [comment]
@kyri-petrou Could you please give more details (version of Scala used, exact error message, etc.).

**Comment by kyri-petrou** [comment]
@plokhotnyuk apologies, I forgot to paste the link earlier 🤦 . Issue seems to be with Scala 2.12.17 and 2.13.10. See failing CI runs for Caliban when upgrading to 2.20.5:

* [Scala 2.12](https://app.circleci.com/pipelines/github/ghostdogpr/caliban/4469/workflows/2e3eb228-fbae-4f31-b678-c2a02235e0cc/jobs/24807)
* [Scala 2.13](https://app.circleci.com/pipelines/github/ghostdogpr/caliban/4469/workflows/2e3eb228-fbae-4f31-b678-c2a02235e0cc/jobs/24815)

From the CI logs:

```shell
[error] /home/circleci/project/core/src/main/scala/caliban/interop/jsoniter/jsoniter.scala:275:69: exception during macro expansion: 
[error] java.io.FileNotFoundException: /home/andriy/Projects/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros/jvm/target/scala-2.12/scoverage-data/scoverage.measurements.61fc5c4e-d8f8-41c1-ab4d-cb4c5f64e533.101 (No such file or directory)
[error] 	at java.base/java.io.FileOutputStream.open0(Native Method)
[error] 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
[error] 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
[error] 	at java.base/java.io.FileWriter.<init>(FileWriter.java:113)
[error] 	at scoverage.Invoker$.$anonfun$invoked$1(Invoker.scala:65)
[error] 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
[error] 	at scoverage.Invoker$.invoked(Invoker.scala:65)
[error] 	at com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker$.<init>(JsonCodecMaker.scala:254)
[error] 	at com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker$.<clinit>(JsonCodecMaker.scala)
[error] 	at com.github.plokhotnyuk.jsoniter_scala.macros.CodecMakerConfig$.<init>(JsonCodecMaker.scala:215)
[error] 	at com.github.plokhotnyuk.jsoniter_scala.macros.CodecMakerConfig$.<clinit>(JsonCodecMaker.scala)
[error] 	at com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker$Impl$.makeWithDefaultConfig(JsonCodecMaker.scala:461)
[error]     private val dtoCodec: JsonValueCodec[ErrorDTO] = JsonCodecMaker.make
```

**Comment by plokhotnyuk** [comment]
@kyri-petrou Thanks a lot! I've found that the source of the problem is due to wrong configuration of `coverageEnabled` flags in `build.sbt`.

I'll fix it finally and cut the v2.10.6 release

**Comment by plokhotnyuk** [comment]
@kyri-petrou  @fggarcia Please peek the v2.20.6 release that finally fixes the issue

**Comment by kyri-petrou** [comment]
Thanks! v2.20.6 works as expected.

By the way I had these issues before; you need to make sure that coverage is **disabled** when you compile the code that will be published. Quickest way to check if the code was compiled with coverage enabled it's to check whether this folder exists under `target/<scala version>`. If it's there and then you run publish, this issue happens.

There's some more info [here](https://github.com/scoverage/sbt-scoverage#usage) on how to disable it as well as some other gotchas
