### ISSUE TITLE
Codecs generated for array based fields of case classes doesn't compile with Scala 2.13.0-M4

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#129]
Compilation error is due missing of the `deep` method.
